import sys
import os
import time

from PyQt4.Qt import *
from PyQt4.QtCore import *
from PyQt4.QtGui import *


os.path.join(os.path.dirname(__file__),
             os.pardir,
             os.pardir,
             os.pardir)

import status
import actions


from properties_base import PropertiesBase

class MemoryBusProperties(PropertiesBase):

    def __init__(self):
        super (MemoryBusProperties, self).__init__()
        self.actions = actions.Actions()
        self.status = status.Status()

        self.set_name("Memory Bus")
        self.set_info("Facilitates communication between master and memory cores\n"
                      "\n"
                      "this core is generated by ibuilder.\n"
                      "\n"
                      "There are a total of 2^32 32-bit address for memory, all memories will be layed out in a contiguous fashion presetning a flat memory to the user\n"
                      "\n"
                      "Communication between a specific memory device is controlled by the connected core in the asociated address space\n")
        self.hide()


    def set_config_dict(self, config_dict):
        self.config_dict = config_dict
        #Setup the reset of the config dict
