import sys
import os
import time

from PyQt4.Qt import *
from PyQt4.QtCore import *
from PyQt4.QtGui import *


os.path.join(os.path.dirname(__file__),
             os.pardir,
             os.pardir,
             os.pardir)

import status
import actions


from properties_base import PropertiesBase

class PeripheralBusProperties(PropertiesBase):

    def __init__(self):
        super (PeripheralBusProperties, self).__init__()
        self.actions = actions.Actions()
        self.status = status.Status()

        self.set_name("Peripheral Bus")
        self.set_info("Facilitates communication between master and user host\n"
                      "this core is generated by ibuilder.\n"
                      "\n"
                      "There are a total of 256 2^24 32-bit address spaces for each peripheral\n"
                      "The first three offsets of peripheral devices include:\n"
                      "\t0x00000000\n"
                      "\t0x01000000\n"
                      "\t0x02000000\n"
                      "\n"
                      "Offset 0x00 is reserved for DRT\n"
                      "Offset 0xFF is reserved for Interrupts\n")
        self.hide()


    def set_config_dict(self, config_dict):
        self.config_dict = config_dict
        #Setup the reset of the config dict
