#! /usr/bin/python

import sys

#It is strange that I have to execute this without a py extension but if I used the py extension
#Then the system would try and use scons as the build environment

def post_build_errors(self, errors):
    for error in errors:
        print "Error: %s" % str(error)

if __name__ == "__main__":
    args = sys.argv
    print "Post execute main"
    for a in args:
        print "Arg: %s" % str(a)
